services:
  sqlserver:
    image: mcr.microsoft.com/azure-sql-edge:latest
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "YourStr0ngPassw0rd!"
    ports:
      - "1433:1433"
    volumes:
      - sqldata:/var/opt/mssql

  localstack:
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
    environment:
      - SERVICES=sqs
      - DEFAULT_REGION=ap-southeast-2
    volumes:
      - "./scripts/init-localstack.sh:/etc/localstack/init/ready.d/init.sh"

volumes:
  sqldata:
